// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using renteasy_api.Infrastructure.Data;

#nullable disable

namespace renteasy_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AccountState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_state");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<DateTimeOffset>("TokenValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_valid_from");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BillPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_period_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LandlordId")
                        .HasColumnType("uuid")
                        .HasColumnName("landlord_id");

                    b.Property<string>("PdfBlobPath")
                        .HasColumnType("text")
                        .HasColumnName("pdf_blob_path");

                    b.HasKey("Id")
                        .HasName("pk_bills");

                    b.HasIndex("BillPeriodId")
                        .HasDatabaseName("ix_bills_bill_period_id");

                    b.HasIndex("LandlordId")
                        .HasDatabaseName("ix_bills_landlord_id");

                    b.ToTable("bills", (string)null);
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.BillPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LandlordId")
                        .HasColumnType("uuid")
                        .HasColumnName("landlord_id");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period_label");

                    b.Property<Guid>("TenancyId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenancy_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bill_periods");

                    b.HasIndex("LandlordId")
                        .HasDatabaseName("ix_bill_periods_landlord_id");

                    b.HasIndex("TenancyId")
                        .HasDatabaseName("ix_bill_periods_tenancy_id");

                    b.ToTable("bill_periods", (string)null);
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.ConditionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer")
                        .HasColumnName("current_round");

                    b.Property<Guid>("LandlordId")
                        .HasColumnType("uuid")
                        .HasColumnName("landlord_id");

                    b.Property<string>("PdfBlobPath")
                        .HasColumnType("text")
                        .HasColumnName("pdf_blob_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenancyId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenancy_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_condition_reports");

                    b.HasIndex("LandlordId")
                        .HasDatabaseName("ix_condition_reports_landlord_id");

                    b.HasIndex("TenancyId")
                        .HasDatabaseName("ix_condition_reports_tenancy_id");

                    b.ToTable("condition_reports", (string)null);
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.ConditionReportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConditionReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("condition_report_id");

                    b.Property<bool>("ContributedByTenant")
                        .HasColumnType("boolean")
                        .HasColumnName("contributed_by_tenant");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDisputed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disputed");

                    b.Property<Guid>("LandlordId")
                        .HasColumnType("uuid")
                        .HasColumnName("landlord_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PhotoBlobPaths")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_blob_paths");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_condition_report_items");

                    b.HasIndex("ConditionReportId")
                        .HasDatabaseName("ix_condition_report_items_condition_report_id");

                    b.HasIndex("LandlordId")
                        .HasDatabaseName("ix_condition_report_items_landlord_id");

                    b.ToTable("condition_report_items", (string)null);
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.EmailNudgeJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NudgeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nudge_type");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("TenancyId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenancy_id");

                    b.HasKey("Id")
                        .HasName("pk_email_nudge_jobs");

                    b.ToTable("email_nudge_jobs", (string)null);
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("LandlordId")
                        .HasColumnType("uuid")
                        .HasColumnName("landlord_id");

                    b.Property<string>("PhotoBlobPaths")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_blob_paths");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Received")
                        .HasColumnName("status");

                    b.Property<Guid>("TenancyId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenancy_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_requests");

                    b.HasIndex("LandlordId")
                        .HasDatabaseName("ix_maintenance_requests_landlord_id");

                    b.HasIndex("TenancyId")
                        .HasDatabaseName("ix_maintenance_requests_tenancy_id");

                    b.ToTable("maintenance_requests", (string)null);
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AmountConfirmed")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_confirmed");

                    b.Property<Guid>("BillPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_period_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LandlordId")
                        .HasColumnType("uuid")
                        .HasColumnName("landlord_id");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("ReceiptPdfBlobPath")
                        .HasColumnType("text")
                        .HasColumnName("receipt_pdf_blob_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Unpaid")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("BillPeriodId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_bill_period_id");

                    b.HasIndex("LandlordId")
                        .HasDatabaseName("ix_payments_landlord_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<Guid>("LandlordId")
                        .HasColumnType("uuid")
                        .HasColumnName("landlord_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("SizeSqm")
                        .HasColumnType("numeric")
                        .HasColumnName("size_sqm");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.HasIndex("LandlordId")
                        .HasDatabaseName("ix_properties_landlord_id");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.Tenancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LandlordId")
                        .HasColumnType("uuid")
                        .HasColumnName("landlord_id");

                    b.Property<DateTimeOffset?>("MoveOutDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("move_out_date");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenancies");

                    b.HasIndex("LandlordId")
                        .HasDatabaseName("ix_tenancies_landlord_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_tenancies_property_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenancies_tenant_id");

                    b.ToTable("tenancies", (string)null);
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.WaitlistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsLandlordInterest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_landlord_interest");

                    b.HasKey("Id")
                        .HasName("pk_waitlist_entries");

                    b.ToTable("waitlist_entries", (string)null);
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.WelcomePack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LandlordId")
                        .HasColumnType("uuid")
                        .HasColumnName("landlord_id");

                    b.Property<Guid>("TenancyId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenancy_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_welcome_packs");

                    b.HasIndex("LandlordId")
                        .HasDatabaseName("ix_welcome_packs_landlord_id");

                    b.HasIndex("TenancyId")
                        .IsUnique()
                        .HasDatabaseName("ix_welcome_packs_tenancy_id");

                    b.ToTable("welcome_packs", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("renteasy_api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("renteasy_api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("renteasy_api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("renteasy_api.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.Bill", b =>
                {
                    b.HasOne("renteasy_api.Domain.Entities.BillPeriod", "BillPeriod")
                        .WithMany("Bills")
                        .HasForeignKey("BillPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bills_bill_periods_bill_period_id");

                    b.Navigation("BillPeriod");
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.BillPeriod", b =>
                {
                    b.HasOne("renteasy_api.Domain.Entities.Tenancy", "Tenancy")
                        .WithMany("BillPeriods")
                        .HasForeignKey("TenancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bill_periods_tenancies_tenancy_id");

                    b.Navigation("Tenancy");
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.ConditionReport", b =>
                {
                    b.HasOne("renteasy_api.Domain.Entities.Tenancy", "Tenancy")
                        .WithMany("ConditionReports")
                        .HasForeignKey("TenancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_condition_reports_tenancies_tenancy_id");

                    b.Navigation("Tenancy");
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.ConditionReportItem", b =>
                {
                    b.HasOne("renteasy_api.Domain.Entities.ConditionReport", "ConditionReport")
                        .WithMany("Items")
                        .HasForeignKey("ConditionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_condition_report_items_condition_reports_condition_report_id");

                    b.Navigation("ConditionReport");
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.HasOne("renteasy_api.Domain.Entities.Tenancy", "Tenancy")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("TenancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_requests_tenancies_tenancy_id");

                    b.Navigation("Tenancy");
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.Payment", b =>
                {
                    b.HasOne("renteasy_api.Domain.Entities.BillPeriod", "BillPeriod")
                        .WithOne("Payment")
                        .HasForeignKey("renteasy_api.Domain.Entities.Payment", "BillPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_bill_periods_bill_period_id");

                    b.Navigation("BillPeriod");
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.Property", b =>
                {
                    b.HasOne("renteasy_api.Domain.Entities.ApplicationUser", "Landlord")
                        .WithMany()
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_properties_users_landlord_id");

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.Tenancy", b =>
                {
                    b.HasOne("renteasy_api.Domain.Entities.ApplicationUser", "Landlord")
                        .WithMany()
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenancies_users_landlord_id");

                    b.HasOne("renteasy_api.Domain.Entities.Property", "Property")
                        .WithMany("Tenancies")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenancies_properties_property_id");

                    b.HasOne("renteasy_api.Domain.Entities.ApplicationUser", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_tenancies_users_tenant_id");

                    b.Navigation("Landlord");

                    b.Navigation("Property");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.WelcomePack", b =>
                {
                    b.HasOne("renteasy_api.Domain.Entities.Tenancy", "Tenancy")
                        .WithOne("WelcomePack")
                        .HasForeignKey("renteasy_api.Domain.Entities.WelcomePack", "TenancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_welcome_packs_tenancies_tenancy_id");

                    b.Navigation("Tenancy");
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.BillPeriod", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.ConditionReport", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.Property", b =>
                {
                    b.Navigation("Tenancies");
                });

            modelBuilder.Entity("renteasy_api.Domain.Entities.Tenancy", b =>
                {
                    b.Navigation("BillPeriods");

                    b.Navigation("ConditionReports");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("WelcomePack");
                });
#pragma warning restore 612, 618
        }
    }
}
